"use client";
import {useEffect,useMemo,useState} from "react";
import {
  Check,
  ChevronDown,
  Download,
  Flame,
  Mail,
  RotateCcw,
  Share2,
  Sparkles,
  Target,
  Trophy,
  Moon,
  Sun,
} from "lucide-react";
import {SignedIn,SignedOut,SignInButton,UserButton,useAuth} from "@clerk/clerk-react";

const QUESTIONS=[
{category:"Digital Logic",difficulty:"Easy",question:"What is the difference between combinational logic and sequential logic?",terms:["input","memory","state","flip-flop"],ideal:"Combinational logic produces an output based only on its current inputs. Sequential logic also depends on stored state from earlier inputs, usually held in memory elements such as flip-flops or registers."},
{category:"Computer Architecture",difficulty:"Easy",question:"What does a CPU cache do, and why is it faster than main memory?",terms:["frequent","data","close","cpu","latency"],ideal:"A CPU cache stores frequently used data and instructions close to the processor. It uses faster memory and has much lower access latency than main memory, so the CPU spends less time waiting for data."},
{category:"Embedded Systems",difficulty:"Medium",question:"What is an interrupt, and when would you use one instead of polling?",terms:["event","pause","handler","cpu","polling"],ideal:"An interrupt is a signal that temporarily pauses normal execution and runs a handler for an event. I would use it when a device needs a fast response without making the CPU repeatedly check its status, as polling would."},
{category:"FPGA & Debugging",difficulty:"Medium",question:"Your FPGA design works in simulation but not on the physical board. What would you check first?",terms:["pin","clock","reset","timing","voltage"],ideal:"I would verify the pin assignments, power and voltage levels, clock and reset signals, and that the correct bitstream was programmed. Then I would review timing constraints and probe signals stage by stage to isolate the mismatch."}];
type Result={score:number;label:string;hits:string[];misses:string[]};
type Theme = "light" | "dark";
function streakFrom(dates:string[]){const days=new Set(dates),cursor=new Date();let total=0;for(;;){const key=cursor.toISOString().slice(0,10);if(!days.has(key))break;total++;cursor.setUTCDate(cursor.getUTCDate()-1)}return total}

export default function Home(){
 const {isSignedIn,getToken}=useAuth();
 const [answer,setAnswer]=useState(""),
  [result,setResult]=useState<Result|null>(null),
  [rewrite,setRewrite]=useState(false),
  [menu,setMenu]=useState(false),
  [shareOpen,setShareOpen]=useState(false),
  [shareFormat,setShareFormat]=useState<"story"|"wide">("story");
 const [streak,setStreak]=useState(0),[played,setPlayed]=useState(0);
 const [completedDates,setCompletedDates]=useState<string[]>([]);
 const [theme,setTheme]=useState<Theme>("light");
 const today=new Date().toISOString().slice(0,10),number=Math.max(1,Math.floor((Date.now()-new Date("2026-09-01").getTime())/86400000)+1);
 const q=useMemo(()=>QUESTIONS[(number-1)%QUESTIONS.length],[number]);
 useEffect(()=>{const saved=localStorage.getItem("interviewdle-theme");if(saved==="dark"||saved==="light")setTheme(saved)},[]);
 useEffect(()=>{document.documentElement.dataset.theme=theme;localStorage.setItem("interviewdle-theme",theme)},[theme]);
 useEffect(()=>{const s=JSON.parse(localStorage.getItem("interviewdle")||"{}");const dates:string[]=Array.isArray(s.completedDates)?s.completedDates:(s.date&&s.result?[s.date]:[]);setCompletedDates(dates);setStreak(streakFrom(dates));setPlayed(dates.length);if(s.date===today&&s.result){setAnswer(s.answer||"");setResult(s.result)}},[today]);
 useEffect(()=>{if(!isSignedIn)return;void (async()=>{const token=await getToken();const response=await fetch("/api/progress",{headers:{Authorization:`Bearer ${token}`}});if(!response.ok)return;const data=await response.json(),dates:string[]=data.dates||[];setCompletedDates(dates);setPlayed(dates.length);setStreak(streakFrom(dates));const latest=data.latest;if(latest?.question_date===today){const saved={score:latest.score_tenths/10,label:latest.result_label,hits:JSON.parse(latest.hits_json),misses:JSON.parse(latest.misses_json)};setAnswer(latest.answer);setResult(saved)}})()},[isSignedIn,getToken,today]);
 async function saveProgress(clean:string,next:Result){if(!isSignedIn)return;const token=await getToken();await fetch("/api/progress",{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${token}`},body:JSON.stringify({date:today,answer:clean,score:next.score,label:next.label,hits:next.hits,misses:next.misses})})}
 function submit(){const clean=answer.trim();if(clean.length<18)return;const signals=["in conclusion","it is important to note","furthermore","plays a crucial role","delve"];if((clean.length>420||signals.filter(x=>clean.toLowerCase().includes(x)).length>=2)&&!rewrite){setRewrite(true);return}const low=clean.toLowerCase(),hits=q.terms.filter(t=>low.includes(t)),misses=q.terms.filter(t=>!low.includes(t));const score=Math.min(10,Math.round((5.2+hits.length*.9+Math.min(clean.length/180,1)*1.2)*10)/10),next={score,label:score>=8.5?"Strong":score>=7?"Good start":"Needs work",hits,misses};const dates=completedDates.includes(today)?completedDates:[today,...completedDates];setCompletedDates(dates);setResult(next);setRewrite(false);setStreak(streakFrom(dates));setPlayed(dates.length);localStorage.setItem("interviewdle",JSON.stringify({date:today,answer:clean,result:next,completedDates:dates}));void saveProgress(clean,next)}
 return <main className="min-h-screen"><header className="topbar"><div className="brand"><span className="brand-mark" aria-hidden="true"><Sun size={19}/></span><span>INTERVIEWDLE</span></div><div className="header-stats"><span><Flame size={18}/>{streak} day streak</span><span className="desktop-only"><Trophy size={17}/>{played} completed</span><div className="theme-picker" role="group" aria-label="Color theme"><button className={theme==="light"?"active":""} onClick={()=>setTheme("light")} aria-label="Use light theme" title="Light theme"><Sun size={16}/></button><button className={theme==="dark"?"active":""} onClick={()=>setTheme("dark")} aria-label="Use dark theme" title="Dark theme"><Moon size={16}/></button></div><SignedOut><SignInButton mode="modal"><button className="sign-in">Sign in</button></SignInButton></SignedOut><SignedIn><UserButton/></SignedIn></div></header>
 <div className="shell"><section className="career-row"><div><p className="eyebrow">YOUR CAREER</p><button className="career-select" onClick={()=>setMenu(!menu)}><span className="chip-icon">⌁</span>Computer Hardware Engineer<ChevronDown size={17}/></button>{menu&&<div className="career-menu"><button onClick={()=>setMenu(false)}><Check size={16}/>Computer Hardware Engineer</button><p>More careers coming soon</p></div>}</div><div className="mini-stats"><div><b>{streak}</b><span>DAY STREAK</span></div><div><b>{played?Math.round(((played-1)*82+Math.max(result?.score||0,7)*10)/played):0}%</b><span>AVG. SCORE</span></div></div></section>
 <section className="game-card"><div className="card-head"><div><p className="eyebrow">TODAY&apos;S INTERVIEW</p><h1>Interviewdle <span>#{String(number).padStart(3,"0")}</span></h1></div><div className="tags"><span>{q.category}</span><span className="difficulty">● {q.difficulty}</span></div></div><div className="question-wrap"><span className="question-number">Q</span><h2>{q.question}</h2></div>
 {!result?<><SignedOut><div className="save-note"><span>Play as a guest, or </span><SignInButton mode="modal"><button>sign in to save progress across devices</button></SignInButton>.</div></SignedOut><label htmlFor="answer">Answer like you&apos;re speaking to an interviewer.</label><div className={`answer-box ${rewrite?"warn":""}`}><textarea id="answer" value={answer} onChange={e=>setAnswer(e.target.value)} placeholder="Explain it in your own words…" maxLength={900}/><span>{answer.length}/900</span></div>{rewrite&&<div className="rewrite"><Sparkles size={20}/><div><b>This answer sounds unusually polished.</b><p>Try explaining it again in your own words, like you would in a real interview.</p></div></div>}<button className="submit" onClick={submit} disabled={answer.trim().length<18}>{rewrite?"Check My Rewrite":"Submit Answer"}<span>↵</span></button><p className="privacy"><Target size={15}/>Your response is checked for learning—not used to accuse or penalize you.</p></>:
 <section className="results"><div className="score-row"><div className="score-badge"><b>{result.score}</b><span>/ 10</span></div><div><p className="eyebrow">YOUR RESULT</p><h3>{result.label}</h3><p>Own Words Check passed — your answer sounds natural.</p></div></div><div className="feedback-grid"><article><h4>What you covered</h4>{result.hits.length?result.hits.map(x=><p key={x}><Check size={16}/>{x}</p>):<p>Try adding more technical detail.</p>}</article><article><h4>What to add</h4>{result.misses.slice(0,3).map(x=><p key={x}><span>+</span>{x}</p>)}</article></div><article className="ideal"><p className="eyebrow">INTERVIEW-READY ANSWER</p><p>“{q.ideal}”</p></article><div className="result-footer">   <span><Flame size={20}/>{streak} day streak</span>    <div className="result-actions">     <button onClick={()=>setShareOpen(!shareOpen)}>       <Share2 size={16}/>       Share Result     </button>      <button onClick={()=>{setAnswer("");setResult(null);setRewrite(false);setShareOpen(false)}}>       <RotateCcw size={16}/>       Replay demo     </button>   </div> </div>  {shareOpen && (   <div className="share-panel">     <div className="share-panel-head">       <div>         <p className="eyebrow">SHARE YOUR RESULT</p>         <h4>Choose a format</h4>       </div>     </div>      <div className="share-formats">       <button         className={shareFormat==="story" ? "active" : ""}         onClick={()=>setShareFormat("story")}       >         <span>9:16</span>         Instagram Story       </button>        <button         className={shareFormat==="wide" ? "active" : ""}         onClick={()=>setShareFormat("wide")}       >         <span>16:9</span>         Desktop / Social       </button>     </div>      <div className={`share-preview ${shareFormat}`}>       <p className="share-brand">INTERVIEWDLE</p>       <p className="share-number">         Interviewdle #{String(number).padStart(3,"0")}       </p>        <div className="share-score">         <b>{result.score}</b>         <span>/10</span>       </div>        <h3>{result.label}</h3>        <div className="share-details">         <span>{q.category}</span>         <span>{streak} day streak</span>       </div>        <p className="share-tagline">         One question. Every day. A better answer each time.       </p>     </div>      <div className="share-buttons">       <button onClick={downloadShareImage}>         <Download size={16}/>         Save Image       </button>        <button onClick={shareResult}>         <Share2 size={16}/>         Share       </button>      <button onClick={shareToX}>
    𝕏
    Post to X
  </button>    <button onClick={emailResult}>         <Mail size={16}/>         Email       </button>     </div>   </div> )}</section>}
 </section><footer><span>One question. Every day. A better answer each time.</span><span>Built for real interview practice.</span></footer></div></main>}